//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLauncher.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingUpdate
    {
        public int SettingUpdateId { get; set; }
        public bool Update { get; set; }
        public Nullable<int> SettingVersion { get; set; }
    }
}
