//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ButtonStyle
{
    public int ButtonStyleId { get; set; }
    public Nullable<int> Width { get; set; }
    public Nullable<int> Height { get; set; }
    public Nullable<int> BackgroundColor { get; set; }
    public byte[] BackgroundImage { get; set; }
    public byte[] Icon { get; set; }
    public string Font { get; set; }
    public Nullable<int> FontSize { get; set; }
    public string FontStyle { get; set; }
}
