//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public string Url { get; set; }
    }
}
