//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RelayServer.DataContext
{

    public partial class ButtonStyle
    {
        public int ButtonStyleId { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> BackgroundColor { get; set; }
        public byte[] BackgroundImage { get; set; }
        public byte[] Icon { get; set; }
        public string Font { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string FontStyle { get; set; }
    }
}