//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLauncher.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrorsSet
    {
        public int Id { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> DateError { get; set; }
        public string ExeName { get; set; }
        public string NameError { get; set; }
        public string DescrError { get; set; }
    }
}
