//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RelayServer.DataContext
{

    public partial class ProviderFile
    {
        public int ProviderFileId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public Nullable<long> FileSize { get; set; }
        public byte[] FileContent { get; set; }

        public virtual Provider Provider { get; set; }
    }
}