//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLauncher.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrors
    {
        public int Id { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> DateError { get; set; }
        public string ExeName { get; set; }
        public string NameError { get; set; }
        public string DescrError { get; set; }
    }
}
