//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLauncher.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAccount
    {
        public int ProviderAccountId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Uri { get; set; }
        public int ProviderId { get; set; }
        public bool Enable { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
